language: php

sudo: false

cache:
    directories:
      - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

install:
  - composer install

before_script:
  - chmod -R 0777 test/rg/injektor/_factories/
  - 'if [ "${TRAVIS_PHP_VERSION}" != "nightly" ]; then phpenv config-rm xdebug.ini ; fi'
